### PR TITLE
[Update|Architecture Content|Design pattern] Fix typos

### PR DESCRIPTION
**Pull request by ckittel**
- No functional changes
- Just typo fixes

### CODE REVIEW

**Comment by ckittel** [comment]
#sign-off and ready for review @meganbradley, @mattbriggs, @jamarw

**Comment by mattbriggs** [comment]
#sign-off @jamarw

**Review by mattbriggs — APPROVED** [review]

**Comment by ckittel** [comment]
What are next steps here @mattbriggs and @jamarw?  Still need another review by someone?

@mattbriggs, any chance you can co-own this repo to support a more direct way to keep these templates up to date?

**Comment by mattbriggs** [comment]
@meganbradley Would to be posisble to merge? Thanks! Matt

**Pull request merged**
